/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.edu.vttu.ui;

import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import vn.edu.vttu.data.Table;
import vn.edu.vttu.data.VariableStatic;
import vn.edu.vttu.data.ConnectDB;

/**
 *
 * @author nhphuoc
 */
public class PanelChangeReservation extends javax.swing.JPanel {

    /**
     * Creates new form frmChageReservation
     */
    private Connection conn;
    private int idTable;
    private String nameTable;
    private String date;
    private int statusBG = -1;

    public PanelChangeReservation() {
        initComponents();
        loadTable();
        //tbChangeReservation.setRowSelectionInterval(0, 0);        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
        Date date = null;
        try {
            date = sdf.parse(VariableStatic.getDateTimeReservation());
        } catch (ParseException ex) {
            Logger.getLogger(PanelViewReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
        dtDateReservation.setDate(date);
        //JOptionPane.showMessageDialog(getRootPane(), VariableStatic.getDateTimeReservation());
    }

    private void loadTable() {
        conn = ConnectDB.conn();
        tbChangeReservation.setModel(Table.loadTableByStatus(conn));
        conn = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtDateReservation = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbChangeReservation = new javax.swing.JTable();
        txtSearchTable = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        dtDateReservation.setDate(new Date());
        dtDateReservation.setDateFormatString("dd/MM/yyyy HH:mm");
        dtDateReservation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dtDateReservation.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtDateReservationPropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Chọn Ngày");

        tbChangeReservation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbChangeReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbChangeReservation.setRowHeight(23);
        tbChangeReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbChangeReservationMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbChangeReservation);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("Tìm Bàn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearchTable, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtDateReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtDateReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearchTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dtDateReservationPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtDateReservationPropertyChange
        String a, b[], c[], c1, c2, c3, d[], e, f, g;
        a = dtDateReservation.getDate().toLocaleString();
        b = a.split(" ");
        c = b[1].split("-");
        c1 = c[0];
        c2 = c[1];
        c3 = c[2];
        d = b[0].split(":");
        e = d[0];
        f = d[1];
        //Date dt = new Date(a);
        String x = c3 + "-" + c2 + "-" + c1 + " " + e + ":" + f + ":00";
        VariableStatic.setDateTimeReservation(x);
        //JOptionPane.showMessageDialog(getRootPane(), VariableStatic.getDateTimeReservation());


    }//GEN-LAST:event_dtDateReservationPropertyChange

    private void tbChangeReservationMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbChangeReservationMouseReleased
        int index = tbChangeReservation.getSelectedRow();
        VariableStatic.setIdTable(Integer.parseInt(String.valueOf(tbChangeReservation.getValueAt(index, 0))));
    }//GEN-LAST:event_tbChangeReservationMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dtDateReservation;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbChangeReservation;
    private javax.swing.JTextField txtSearchTable;
    // End of variables declaration//GEN-END:variables
}
