/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vn.edu.vttu.ui;

/**
 *
 * @author nhphuoc
 */
public class PanelMenuStatistics extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuStatistics
     */
    public PanelMenuStatistics() {
        initComponents();
        pnThongKeDoanhThu.add(new PanelStatiticsRevenue());
        pnThongKeDoanhThu.updateUI();
        pnThongKeDoanhThu.repaint();
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnThongKeDoanhThu = new javax.swing.JPanel();
        pnThongKeDichVu = new javax.swing.JPanel();
        pnThongKeNguyenLieu = new javax.swing.JPanel();
        pnThongKeChi = new javax.swing.JPanel();
        pnThongKeThuChi = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout());

        jTabbedPane1.setForeground(new java.awt.Color(0, 51, 255));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        pnThongKeDoanhThu.setLayout(new java.awt.GridLayout());
        jTabbedPane1.addTab("Thống Kê Doanh Thu", pnThongKeDoanhThu);

        javax.swing.GroupLayout pnThongKeDichVuLayout = new javax.swing.GroupLayout(pnThongKeDichVu);
        pnThongKeDichVu.setLayout(pnThongKeDichVuLayout);
        pnThongKeDichVuLayout.setHorizontalGroup(
            pnThongKeDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
        );
        pnThongKeDichVuLayout.setVerticalGroup(
            pnThongKeDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thống Kê Dịch Vụ", pnThongKeDichVu);

        javax.swing.GroupLayout pnThongKeNguyenLieuLayout = new javax.swing.GroupLayout(pnThongKeNguyenLieu);
        pnThongKeNguyenLieu.setLayout(pnThongKeNguyenLieuLayout);
        pnThongKeNguyenLieuLayout.setHorizontalGroup(
            pnThongKeNguyenLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
        );
        pnThongKeNguyenLieuLayout.setVerticalGroup(
            pnThongKeNguyenLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thống Kê Nguyên Liệu", pnThongKeNguyenLieu);

        javax.swing.GroupLayout pnThongKeChiLayout = new javax.swing.GroupLayout(pnThongKeChi);
        pnThongKeChi.setLayout(pnThongKeChiLayout);
        pnThongKeChiLayout.setHorizontalGroup(
            pnThongKeChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
        );
        pnThongKeChiLayout.setVerticalGroup(
            pnThongKeChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thống Kê Chi", pnThongKeChi);

        javax.swing.GroupLayout pnThongKeThuChiLayout = new javax.swing.GroupLayout(pnThongKeThuChi);
        pnThongKeThuChi.setLayout(pnThongKeThuChiLayout);
        pnThongKeThuChiLayout.setHorizontalGroup(
            pnThongKeThuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
        );
        pnThongKeThuChiLayout.setVerticalGroup(
            pnThongKeThuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thống Kê Thu - Chi", pnThongKeThuChi);

        add(jTabbedPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnThongKeChi;
    private javax.swing.JPanel pnThongKeDichVu;
    private javax.swing.JPanel pnThongKeDoanhThu;
    private javax.swing.JPanel pnThongKeNguyenLieu;
    private javax.swing.JPanel pnThongKeThuChi;
    // End of variables declaration//GEN-END:variables
}
