/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.edu.vttu.ui;

import java.awt.Component;
import java.sql.Connection;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JList;
import javax.swing.plaf.basic.BasicComboBoxRenderer;
import vn.edu.vttu.data.ConnectDB;
import vn.edu.vttu.data.Table;
import vn.edu.vttu.data.TableLocation;
import vn.edu.vttu.data.VariableStatic;

/**
 *
 * @author nhphuoc
 */
public class PanelChangeTable extends javax.swing.JPanel {

    class ItemRendererTableLocation extends BasicComboBoxRenderer {

        public Component getListCellRendererComponent(
                JList list, Object value, int index,
                boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index,
                    isSelected, cellHasFocus);

            if (value != null) {
                vn.edu.vttu.model.TableLocation item = (vn.edu.vttu.model.TableLocation) value;
                // đây là thông tin ta sẽ hiển thị , đối bảng khác sẽ khác cột chúng ta sẽ đổi lại tên tương ứng
                setText(item.getName().toUpperCase());
            }

            if (index == -1) {
                vn.edu.vttu.model.TableLocation item = (vn.edu.vttu.model.TableLocation) value;
                setText("" + item.getName());
            }

            return this;
        }
    }

    class ItemRendererTable extends BasicComboBoxRenderer {

        public Component getListCellRendererComponent(
                JList list, Object value, int index,
                boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index,
                    isSelected, cellHasFocus);

            if (value != null) {
                vn.edu.vttu.model.Table item = (vn.edu.vttu.model.Table) value;
                setText(String.valueOf(item.getNameTable()));
            }

            if (index == -1) {
                vn.edu.vttu.model.Table item = (vn.edu.vttu.model.Table) value;
                setText("" + String.valueOf(item.getNameTable()));
            }

            return this;
        }
    }

    /**
     * Creates new form PanelChangeTable
     */
    private Connection conn;

    public PanelChangeTable() {
        initComponents();
        try {
            fillcobTableLocation();
            vn.edu.vttu.model.TableLocation tbLocation = (vn.edu.vttu.model.TableLocation) cobTableLocation.getSelectedItem();
            int idLocation = tbLocation.getId();
            fillComboTable(idLocation);
            vn.edu.vttu.model.Table tb = (vn.edu.vttu.model.Table) cobTable.getSelectedItem();
            int idTable = tb.getIdTable();
            VariableStatic.setIdTable_Change(idTable);
        } catch (Exception e) {
            System.out.println("Lỗi khi khởi động form: "+e.getMessage());
        }

    }

    private void fillcobTableLocation() {
        conn = ConnectDB.conn();
        Vector<vn.edu.vttu.model.TableLocation> model = new Vector<vn.edu.vttu.model.TableLocation>();
        try {
            model = TableLocation.selectTableLocation(ConnectDB.conn());
        } catch (Exception e) {
            System.out.println("Lỗi dổ dữ liệu vào combobox Location: "+e.getMessage());
        }

        DefaultComboBoxModel defaultComboBoxModel = new javax.swing.DefaultComboBoxModel(model);
        cobTableLocation.putClientProperty("JComboBox.isTableCellEditor", Boolean.TRUE);
        cobTableLocation.setModel(defaultComboBoxModel);
        cobTableLocation.setRenderer(new PanelChangeTable.ItemRendererTableLocation());
        conn = null;
    }

    private void fillComboTable(int idLocation) {
        conn = ConnectDB.conn();
        Vector<vn.edu.vttu.model.Table> model = new Vector<vn.edu.vttu.model.Table>();
        try {
            model = Table.selectTableByLocation(idLocation,1, ConnectDB.conn());
        } catch (Exception e) {            
        }

        DefaultComboBoxModel defaultComboBoxModel = new javax.swing.DefaultComboBoxModel(model);
        cobTable.putClientProperty("JComboBox.isTableCellEditor", Boolean.TRUE);
        cobTable.setModel(defaultComboBoxModel);
        cobTable.setRenderer(new PanelChangeTable.ItemRendererTable());
        conn = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cobTableLocation = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cobTable = new javax.swing.JComboBox();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("Chọn Vị Trí");

        cobTableLocation.setEditable(true);
        cobTableLocation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cobTableLocationItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("Chọn Bàn");

        cobTable.setEditable(true);
        cobTable.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cobTableItemStateChanged(evt);
            }
        });
        cobTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cobTablePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cobTable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cobTableLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cobTableLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cobTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cobTableLocationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cobTableLocationItemStateChanged
        try {
            vn.edu.vttu.model.TableLocation tbLocation = (vn.edu.vttu.model.TableLocation) cobTableLocation.getSelectedItem();
            int idLocation = tbLocation.getId();
            fillComboTable(idLocation);
        } catch (Exception e) {            
        }


    }//GEN-LAST:event_cobTableLocationItemStateChanged

    private void cobTableItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cobTableItemStateChanged

    }//GEN-LAST:event_cobTableItemStateChanged

    private void cobTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cobTablePropertyChange
        try {
            vn.edu.vttu.model.Table tb = (vn.edu.vttu.model.Table) cobTable.getSelectedItem();
            int idTable = tb.getIdTable();
            VariableStatic.setIdTable_Change(idTable);
        } catch (Exception e) {            
        }

    }//GEN-LAST:event_cobTablePropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cobTable;
    private javax.swing.JComboBox cobTableLocation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
